name: Deploy to DEV Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}  # Use the SSH key stored in GitHub secrets
          script: |
            cd /var/www/maileditor/html
            git pull origin main  # Ensure you're pulling the latest code
            composer install
            php artisan migrate --force  # Run migrations, if necessary
    
          
